<?php
require_once 'dataconnect/dbconnect.php';
	$dokho = 1;
	$ngaythem = date("Y/m/d");

	$someJSON = '[
      {"ques":"Việc đưa ra các quy định về thuế, pháp luật đã tác động đến lĩnh vực",
        "ans_a":"A. Môi trường",
        "ans_b":"B. Kinh tế",
        "ans_c":"C. Văn hóa",
        "ans_d":"D. Quốc phòng an ninh","ans_true":	2	},
      {"ques":"Đối với sự phát triển kinh tế - xã hội, văn hóa được xem là",
        "ans_a":"A. Điều kiện",
        "ans_b":"B. Cơ sở",
        "ans_c":"C. Tiền đề",
        "ans_d":"D. Động lực","ans_true":	4	},
      {"ques":"Thực hiện trách nhiệm pháp lý đối với người từ đủ 14 đến dưới 18 tuổi là",
        "ans_a":"A. Giáo dục, răn đe là chính",
        "ans_b":"B. Có thể bị phạt tù",
        "ans_c":"C. Buộc phải cách li với xã hội và không có điều kiện tái hòa nhập cộng đồng",
        "ans_d":"D. Chủ yếu là đưa ra lời khuyên","ans_true":	1	},
      {"ques":"Trách nhiệm pháp lý được áp dụng đối với người vi phạm pháp luật nhằm",
        "ans_a":"A. giáo dục, răn đe, hành hạ",
        "ans_b":"B. kiềm chế những việc làm trái luật",
        "ans_c":"C. xử phạt hành chính",
        "ans_d":"D. phạt tù hoặc tử hình","ans_true":	2	},
      {"ques":"Vi phạm pháp luật hành chính là hành vi vi phạm pháp luật, xâm phạm tới",
        "ans_a":"A. quan hệ xã hội và quan hệ kinh tế",
        "ans_b":"B. các quy tắc quản lí nhà nước",
        "ans_c":"C. các điều luật và các quan hệ hành chính",
        "ans_d":"D. quan hệ xã hội và quan hệ hành chính","ans_true":	2	},
      {"ques":"Hình phạt trong pháp luật hình sự của các nước thể hiện “hậu quả pháp lý” nặng nề nhất mà chủ thể phải gánh chịu do hành vi vi phạm pháp luật gây ra thể hiện đặc trưng",
        "ans_a":"A. Tính xác định chặt chẽ về mặt hình thức",
        "ans_b":"B. Tính quyền lực, bắt buộc chung",
        "ans_c":"C. Tính chủ quan, quy phạm phổ biến",
        "ans_d":"D. Tính ý chí","ans_true":	2	},
      {"ques":"Một học sinh lớp 11 (16 tuổi) chạy xe gắn máy trên 50cc ra đường chơi (Có đội mũ bảo hiểm), được xem là",
        "ans_a":"A. Không vi phạm pháp luật vì thực hiện quyền tự do đi lại",
        "ans_b":"B. Vi phạm pháp luật vì có đủ năng lực trách nhiệm pháp lý",
        "ans_c":"C. Không phải chịu trách nhiệm về hành vi của mình",
        "ans_d":"D. Không vi phạm vì có đội mũ bảo hiểm theo quy định","ans_true":	4	},
      {"ques":"Cứ đến ngày Quốc khánh (2/9) người nào cải tạo tốt, biết hối cải thì được Chủ tịch nước ân xá cho ra tù trước thời hạn. Thể hiện bản chất gì của pháp luật?",
        "ans_a":"A. Bản chất giai cấp",
        "ans_b":"B. Bản chất xã hội",
        "ans_c":"C. Bản chất nhân đạo sâu sắc pháp luật xã hội chủ nghĩa",
        "ans_d":"D. Bản chất nhân dân","ans_true":	1	},
      {"ques":"Khoan hồng đối với người tự thú, thành khẩn khai báo, tố giác người đồng phạm, lập công chuộc tội, ăn năn hối cải, tự nguyện sửa chữa hoặc bồi thường thiệt hại gây ra. Thể hiện điều gì của pháp luật nước ta",
        "ans_a":"A. tính nhân đạo",
        "ans_b":"B. tính quyền lực",
        "ans_c":"C. tính dân chủ",
        "ans_d":"D. tính xã hội","ans_true":	1	},
      {"ques":"Tòa án huyện A tuyên bố bị cáo B mức phạt 2 năm tù vì tội hiếp dâm, là",
        "ans_a":"A. Sử dụng pháp luật",
        "ans_b":"B. Áp dụng pháp luật",
        "ans_c":"C. Thi hành pháp luật",
        "ans_d":"D. Tuân thủ pháp luật","ans_true":	1	},
      {"ques":"Quyền sáng tạo của công dân được pháp luật quy định là",
        "ans_a":"A. Quyền sở hữu công nghiệp",
        "ans_b":"B. Quyền được tự do thông tin",
        "ans_c":"C. Quyền tự do ngôn luận, tự do báo chí",
        "ans_d":"D. Quyền phát triển","ans_true":	1	},
      {"ques":"Nhà nước thực hiện công bằng xã hội trong giáo dục là để",
        "ans_a":"A. tạo điều kiện cho ai cũng được học hành",
        "ans_b":"B. mọi công dân bình đẳng, nhưng phải có sự đồng ý của cơ quan có thẩm quyền",
        "ans_c":"C. ưu tiên cho các dân tộc thiểu số",
        "ans_d":"D. ưu tiên tìm tòi nhân tài, góp phần phụng sự đất nước","ans_true":	1	},
      {"ques":"Các tổ chức cá nhân không làm những việc bị cấm là",
        "ans_a":"A. Sử dụng pháp luật",
        "ans_b":"B. Thi hành pháp luật",
        "ans_c":"C. Tuân thủ pháp luật",
        "ans_d":"D. Áp dụng pháp luật","ans_true":	3	},
      {"ques":"Dấu hiệu cơ bản của vi phạm pháp luật là",
        "ans_a":"A. hành vi trái pháp luật",
        "ans_b":"B. hành vi không đúng luật",
        "ans_c":"C. hành vi sai pháp luật",
        "ans_d":"D. hành vi không có trong luật","ans_true":	1	},
      {"ques":"Nhà nước đưa ra trách nhiệm pháp lý là nhằm",
        "ans_a":"A. Phạt tiền người vi phạm",
        "ans_b":"B. Buộc chủ thể vi phạm chấm dứt hành vi trái pháp luật, phải chịu những thiệt hại nhất định; giáo dục răn đe những người khác",
        "ans_c":"C. Lập lại trật tự xã hội",
        "ans_d":"D. Ngăn chặn người vi phạm có thể có vi phạm mới","ans_true":	2	},
      {"ques":"Cơ sở nào sau đây là cơ sở pháp lý bảo đảm bình đẳng quyền và nghĩa vụ của công dân?",
        "ans_a":"A. Hiến pháp, Luật, Bộ luật",
        "ans_b":"B. Nội quy của cơ quan",
        "ans_c":"C. Điều lệ Đoàn",
        "ans_d":"D. Điều lệ Đảng","ans_true":	1	},
      {"ques":"Công dân bình đẳng về quyền và nghĩa vụ được hiểu là",
        "ans_a":"A. Mọi công dân đều được hưởng quyền như nhau theo quy định của pháp luật",
        "ans_b":"B. Mọi công dân đều phải có nghĩa vụ như nhau theo quy định của pháp luật",
        "ans_c":"C. Mọi công dân đều được bình đẳng về hưởng quyền và làm nghĩa vụ trước Nhà nước và xã hội theo quy định của Pháp luật",
        "ans_d":"D. Mọi công dân đều có quyền và nghĩa vụ giống nhau","ans_true":	3	},
      {"ques":"Khi nói đến bình đẳng có thể hiểu là vấn đề nào được đề cập trước hết?",
        "ans_a":"A. Quyền lợi",
        "ans_b":"B. Cách đối xử",
        "ans_c":"C. Trách nhiệm",
        "ans_d":"D. Nghĩa vụ","ans_true":	1	},
      {"ques":"Điều nào sau đây không phải là mục đích của hôn nhân",
        "ans_a":"A. xây dựng gia đình hạnh phúc",
        "ans_b":"B. củng cố tình yêu lứa đôi",
        "ans_c":"C. tổ chức đời sống vật chất của gia đình",
        "ans_d":"D. thực hiện đúng nghĩa vụ của công dân đối với đất nước","ans_true":	3	},
      {"ques":"Bình bẳng trong quan hệ vợ chồng được thể hiện qua quan hệ nào sau đây?",
        "ans_a":"A. Quan hệ vợ chồng và quan hệ giữa vợ chồng với họ hàng nội, ngoại",
        "ans_b":"B. Quan hệ gia đình và quan hệ xã hội",
        "ans_c":"C. Quan hệ nhân thân và quan hệ tài sản",
        "ans_d":"D. Quan hệ hôn nhân và quan hệ quyết thống","ans_true":	3	},
      {"ques":"Nội dung nào sau đây thể hiện bình đẳng trong lao động",
        "ans_a":"A. Cùng thực hiện đúng nghĩa vụ tài chính đối với nhà nước",
        "ans_b":"B. Tự do lựa chọn các hình thức kinh doanh",
        "ans_c":"C. Có cơ hội như nhau trong tiếp cận việc làm",
        "ans_d":"D. Tự chủ trong kinh doanh để nâng cao hiệu quả cạnh tranh","ans_true":	3	},
      {"ques":"Theo Hiến pháp nước ta đối với công dân lao động là",
        "ans_a":"A. Nghĩa vụ",
        "ans_b":"B. Bổn phận",
        "ans_c":"C. Quyền lợi",
        "ans_d":"D. Quyền và nghĩa vụ","ans_true":	4	},
      {"ques":"Sau một thời gian hoạt động, công ty X thu được lãi cao và quyết định mở rộng quy mô ngành nghề của mình. Công ty X đã thực hiện quyền",
        "ans_a":"A. bình đẳng trong lao động",
        "ans_b":"B. bình đẳng trong kinh doanh",
        "ans_c":"C. bình đẳng trong sản xuất",
        "ans_d":"D. bình đẳng trong quan hệ kinh tế - xã hội","ans_true":	2	},
      {"ques":"Chị A muốn nhận B làm con nuôi, theo quy định của pháp luật thì chị A phải thỏa mãn một trong các điều kiện sau",
        "ans_a":"A. Chị A phải từ 20 tuổi trở lên",
        "ans_b":"B. Chị A chỉ cần nộp giấy chứng minh và giấy tờ tùy thân của mình",
        "ans_c":"C. Chị A chỉ cần có sự chứng kiến của cơ quan nhà nước thì có thể nhận B làm con nuôi",
        "ans_d":"D. Chị A phải từ 22 tuổi trở lên","ans_true":	1	},
      {"ques":"Quyền bình đẳng giữa các dân tộc được hiểu là",
        "ans_a":"A. Các dân tộc được nhà nước và pháp luật tôn trọng",
        "ans_b":"B. Các dân tộc được nhà nước và pháp luật bảo vệ",
        "ans_c":"C. Các dân tộc được nhà nước và pháp luật tôn trọng, bảo vệ tạo điều kiện phát triển",
        "ans_d":"D. Các dân tộc được nhà nước và pháp luật tôn trọng, bảo vệ","ans_true":	3	},
      {"ques":"Tôn giáo được biểu hiện",
        "ans_a":"A. Qua các đạo khác nhau",
        "ans_b":"B. Qua các tín ngưỡng",
        "ans_c":"C. Qua các hình thức tín ngưỡng có tổ chức",
        "ans_d":"D. Qua các hình thức lễ nghi","ans_true":	3	},
      {"ques":"Việc các thí sinh dân tộc thiểu số vùng sâu, vùng xa khi thi tuyển đại học được cộng điểm ưu tiên được hiểu là thể hiệ",
        "ans_a":"A. quyền bình đẳng giữa các dân tộc",
        "ans_b":"B. quyền bình đẳng giữa các tôn giáo",
        "ans_c":"C. quyền bình đẳng giữa các công dân",
        "ans_d":"D. quyền bình đẳng giữa các cá nhân","ans_true":	1	},
      {"ques":"Đi xe máy vượt đèn đỏ gây thương tích cho người khác là vi phạm quyền",
        "ans_a":"A. Bất khả xâm phạm về thân thể của công dân",
        "ans_b":"B. Được pháp luật bảo hộ về tính mạng, sức khoẻ của công dân",
        "ans_c":"C. Được pháp luật bảo hộ về danh dự, nhân phẩm của công dân",
        "ans_d":"D. Bất khả xâm phạm về chỗ ở của công dân","ans_true":	2	},
      {"ques":"Giam giữ người quá thời hạn qui định là vi phạm quyền",
        "ans_a":"A. Bất khả xâm phạm về thân thể của công dân",
        "ans_b":"B. Được pháp luật bảo hộ về tính mạng, sức khoẻ của công dân",
        "ans_c":"C. Được pháp luật bảo hộ về danh dự, nhân phẩm của công dân",
        "ans_d":"D. Bất khả xâm phạm về chỗ ở của công dân","ans_true":	1	},
      {"ques":"Xúc phạm người khác trước mặt nhiều người là vi phạm quyền",
        "ans_a":"A. Bất khả xâm phạm về thân thể của công dân",
        "ans_b":"B. Được pháp luật bảo hộ về tính mạng, sức khoẻ của công dân",
        "ans_c":"C. Được pháp luật bảo hộ về danh dự, nhân phẩm của công dân",
        "ans_d":"D. Bất khả xâm phạm về chỗ ở của công dân","ans_true":	3	},
      {"ques":"Vai trò của pháp luật đối với sự phát triển bền vững của đất nước được thể hiện",
        "ans_a":"A. Trong lĩnh vực văn hóa",
        "ans_b":"B. Chủ yếu trong lĩnh vực kinh tế",
        "ans_c":"C. Chủ yếu trong lĩnh vực bảo vệ môi trường",
        "ans_d":"D. Trong tất cả các lĩnh vực của đời sống xã hội","ans_true":	4	},
      {"ques":"Trong xu hướng toàn cầu hóa, quốc tế hóa hiện nay và để đảm bảo sự lâu dài, hiệu quả, mỗi quốc gia nên chọn phát triển theo hướng",
        "ans_a":"A. Năng động",
        "ans_b":"B. Sáng tạo",
        "ans_c":"C. Bền vững",
        "ans_d":"D. Liên tục","ans_true":	3	},
      {"ques":"Quyền bất khả xâm phạm về thân thể của cong dân được ghi nhận tại điều 20 Hiến pháp 2013 là",
        "ans_a":"A. Quyền tự do nhất",
        "ans_b":"B. Quyền tự do cơ bản nhất",
        "ans_c":"C. Quyền tự do quan trọng nhất",
        "ans_d":"D. Quyền tự do cần thiết nhất","ans_true":	3	},
      {"ques":"Trong lúc H đang bận việc riêng thì điện thoại có tin nhắn, T đã tự ý mở điện thoại của H ra đọc tin nhắn. Hành vi này của T đã xâm phạm đến quyền nào dưới đây?",
        "ans_a":"A. Quyền được pháp luật bảo hộ về danh dự của công dân",
        "ans_b":"B. Quyền tự do dân chủ của công dân",
        "ans_c":"C. Quyền được đảm bảo an toàn và bí mật thư tín, điện thoại của công dân",
        "ans_d":"D. Quyền tự do ngôn luận của công dân","ans_true":	3	},
      {"ques":"Trong thời gian gần đây, trên mạng xã hội facebook xuất hiện những clip nhiều nữ sinh đánh bạn học, làm tổn hại nghiêm trọng đến tâm sinh lí của người bị hại là vi phạm nội dung của",
        "ans_a":"A. quyền bất khả xâm phạm về thân thể của công dân",
        "ans_b":"B. quyền được pháp luật bảo hộ về sức khỏe, tính mạng, danh dự và nhân phẩm của công dân",
        "ans_c":"C. quyền bất khả xâm phạm về sức khỏe, tính mạng, danh dự và nhân phẩm của công dân",
        "ans_d":"D. quyền được pháp luật bảo đảm về sức khỏe, tính mạng, danh dự và nhân phẩm của công dân","ans_true":	2	},
      {"ques":"Anh A đề nghị thủ trưởng cơ quan xem xét lại quyết định cho thôi việc của mình. Ta nói anh A đang thực hiện quyền gì?",
        "ans_a":"A. Quyền tố cáo",
        "ans_b":"B. Quyền ứng cử",
        "ans_c":"C. Quyền bãi nại",
        "ans_d":"D. Quyền khiếu nại","ans_true":	4	},
      {"ques":"Nguyên tắc nào không phải là nguyên tắc bầu cử",
        "ans_a":"A. Phổ thông",
        "ans_b":"B. Bình đẳng",
        "ans_c":"C. Công khai",
        "ans_d":"D. Trực tiếp","ans_true":	3	},
      {"ques":"Thảo luận và biểu quyết các các vấn đề trọng đại khi Nhà nước tổ chức trưng cầu ý dân là việc thực hiện quyền tham gia quản lý nhà nước ở",
        "ans_a":"A. Phạm vi cả nước",
        "ans_b":"B. Phạm vi cơ sở",
        "ans_c":"C. Phạm vi địa phương",
        "ans_d":"D. Phạm vi cơ sở và địa phương","ans_true":	2	},
      {"ques":"Tác phẩm văn học do công dân tạo ra được pháp luật bảo hộ thuộc quyền nào dưới đây của công dân?",
        "ans_a":"A. Quyền tác giả",
        "ans_b":"B. Quyền sở hữu công nghiệp",
        "ans_c":"C. Quyền phát minh sáng chế",
        "ans_d":"D. Quyền được phát triển","ans_true":	1	},
      {"ques":"Chính sách miễn giảm học phí của Nhà nước ta đã tạo điều kiện giúp đỡ nhiều học sinh có hoàn cảnh khó khăn được học tập. Điều này thể hiện",
        "ans_a":"A. công bằng xã hội trong giáo dục",
        "ans_b":"B. bất bình đẳng trong giáo dục",
        "ans_c":"C. định hướng đổi mới giáo dục",
        "ans_d":"D. chủ trương phát triển giáo dục","ans_true":	1	}
    ]';

  // Convert JSON string to Array
  $someArray = json_decode($someJSON, true);
  foreach ($someArray as $key => $value) {
    // echo $value["ques"].", ".$value["ans_a"].", ".$value["ans_b"].", ".$value["ans_c"].", ".$value["ans_d"].", ".$value["ans_true"]."<br>";
    if (isset($value['img'])){
    	$img = $value["img"];
    }else $img="";
    $noidung = $value["ques"];
	$dapanA = $value["ans_a"];
	$dapanB = $value["ans_b"];
	$dapanC = $value["ans_c"];
	$dapanD = $value["ans_d"];
	$dapandung = $value["ans_true"];
	// $sql="insert into cauhoi_sinh(ma_monhoc, ngaythem, cauhoi, dapanA, dapanB, dapanC, dapanD, dapandung, dokho, hinhanh) values (4, '$ngaythem', '$noidung','$dapanA','$dapanB','$dapanC','$dapanD',$dapandung,$dokho,'$img')";
 //    $run=getSimpleQuery($sql);
	// $sql = $conn->prepare("insert into cauhoi_gdcd values ('',?,?,?,?,?,?,?,?,?,?,?)");
 //    $data = array(8,$ngaythem,1,$noidung,$dapanA,$dapanB,$dapanC,$dapanD,$dapandung,1,$img);
 //    $sql->execute($data);
  }
?>